"""add alarms and work orders

Revision ID: 195b71ae4147
Revises: e1859c60e5ea
Create Date: 2026-09-15 04:49:53.955456

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '195b71ae4147'
down_revision: Union[str, Sequence[str], None] = 'e1859c60e5ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine_alarms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('alarm_code', sa.String(length=50), nullable=False),
    sa.Column('alarm_message', sa.Text(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_alarms_alarm_code'), 'machine_alarms', ['alarm_code'], unique=False)
    op.create_index(op.f('ix_machine_alarms_machine_id'), 'machine_alarms', ['machine_id'], unique=False)
    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_orders_machine_id'), 'work_orders', ['machine_id'], unique=False)
    op.create_index(op.f('ix_work_orders_order_no'), 'work_orders', ['order_no'], unique=True)
    op.create_index(op.f('ix_work_orders_status'), 'work_orders', ['status'], unique=False)
    op.alter_column('machines', 'last_heartbeat_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('machines', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('machines', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('machines_code_key'), 'machines', type_='unique')
    op.create_index(op.f('ix_machines_code'), 'machines', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_machines_code'), table_name='machines')
    op.create_unique_constraint(op.f('machines_code_key'), 'machines', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('machines', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('machines', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('machines', 'last_heartbeat_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_work_orders_status'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_order_no'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_machine_id'), table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index(op.f('ix_machine_alarms_machine_id'), table_name='machine_alarms')
    op.drop_index(op.f('ix_machine_alarms_alarm_code'), table_name='machine_alarms')
    op.drop_table('machine_alarms')
    # ### end Alembic commands ###
