"""add materials and production records

Revision ID: e0e7345af3cc
Revises: 195b71ae4147
Create Date: 2026-09-15 06:01:56.928662

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e0e7345af3cc'
down_revision: Union[str, Sequence[str], None] = '195b71ae4147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('stock_qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('safe_stock', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('safe_stock >= 0', name='ck_material_safe_stock_non_negative'),
    sa.CheckConstraint('stock_qty >= 0', name='ck_material_stock_qty_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_code'), 'materials', ['code'], unique=True)
    op.create_table('production_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('line_code', sa.String(length=50), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('planned_qty', sa.Integer(), nullable=False),
    sa.Column('actual_qty', sa.Integer(), nullable=False),
    sa.Column('defect_qty', sa.Integer(), nullable=False),
    sa.Column('production_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('actual_qty >= 0', name='ck_production_actual_qty_non_negative'),
    sa.CheckConstraint('defect_qty <= actual_qty', name='ck_production_defect_not_greater_than_actual'),
    sa.CheckConstraint('defect_qty >= 0', name='ck_production_defect_qty_non_negative'),
    sa.CheckConstraint('planned_qty >= 0', name='ck_production_planned_qty_non_negative'),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_records_line_code'), 'production_records', ['line_code'], unique=False)
    op.create_index(op.f('ix_production_records_machine_id'), 'production_records', ['machine_id'], unique=False)
    op.create_index(op.f('ix_production_records_product_code'), 'production_records', ['product_code'], unique=False)
    op.create_index(op.f('ix_production_records_production_date'), 'production_records', ['production_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_records_production_date'), table_name='production_records')
    op.drop_index(op.f('ix_production_records_product_code'), table_name='production_records')
    op.drop_index(op.f('ix_production_records_machine_id'), table_name='production_records')
    op.drop_index(op.f('ix_production_records_line_code'), table_name='production_records')
    op.drop_table('production_records')
    op.drop_index(op.f('ix_materials_code'), table_name='materials')
    op.drop_table('materials')
    # ### end Alembic commands ###
